- parquet-hadoop/src/test/java/org/apache/parquet/statistics/RandomValues.java
The random data generator used for tests used to repeat the same value
over and over again.
> PARQUET-1353: Fix random data generator.

- README.md
brew formula for thrift is `brew install thrift@0.12` not thrift@0.12.0
see https://formulae.brew.sh/formula/thrift
> Correct brew formula for thirft

- parquet-cli/src/main/java/org/apache/parquet/cli/json/AvroJson.java
- parquet-cli/src/main/java/org/apache/parquet/cli/util/Schemas.java
Some fields are deprecated in Avro 1.8.2 and are being removed in Avro 1.9.0, therefore we want to replace these fields.
https://issues.apache.org/jira/browse/PARQUET-1557
> PARQUET-1557 Replace deprecated Avro methods

- parquet-avro/src/test/java/org/apache/parquet/avro/TestGenericLogicalTypes.java
https://jira.apache.org/jira/browse/PARQUET-1577
> PARQUET-1577 Remove duplicate license

- parquet-avro/src/test/java/org/apache/parquet/avro/AvroTestUtil.java
- parquet-avro/src/test/java/org/apache/parquet/avro/TestArrayCompatibility.java
- parquet-avro/src/test/java/org/apache/parquet/avro/TestReadWrite.java
- parquet-avro/src/test/java/org/apache/parquet/avro/TestReadWriteOldListBehavior.java
- parquet-cli/src/main/java/org/apache/parquet/cli/BaseCommand.java
https://jira.apache.org/jira/browse/PARQUET-1558
> PARQUET-1556 Use try-with-resource in Apache Avro tests

- parquet-avro/src/test/java/org/apache/parquet/avro/AvroTestUtil.java
- parquet-avro/src/test/java/org/apache/parquet/avro/TestAvroSchemaConverter.java
- parquet-avro/src/test/java/org/apache/parquet/avro/TestReadWriteOldListBehavior.java
- parquet-avro/src/test/java/org/apache/parquet/avro/TestReflectLogicalTypes.java
- parquet-avro/src/test/java/org/apache/parquet/avro/TestSpecificReadWrite.java
- pom.xml
https://jira.apache.org/jira/browse/PARQUET-1576
> PARQUET-1576 Bump Apache Avro to 1.9.0

- parquet-column/src/main/java/org/apache/parquet/filter2/predicate/UserDefinedPredicate.java
- parquet-column/src/main/java/org/apache/parquet/internal/column/columnindex/ColumnIndexBuilder.java
- parquet-column/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java
- parquet-column/src/test/java/org/apache/parquet/internal/column/columnindex/TestColumnIndexBuilder.java
- parquet-generator/src/main/java/org/apache/parquet/filter2/IncrementallyUpdatedFilterPredicateGenerator.java
- parquet-hadoop/src/main/java/org/apache/parquet/filter2/dictionarylevel/DictionaryFilter.java
- parquet-hadoop/src/main/java/org/apache/parquet/filter2/statisticslevel/StatisticsFilter.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestColumnIndexFiltering.java
Modified the existing tests TestColumnIndexBuilder.java and TestColumnIndexFiltering.java to cover the scenario
> PARQUET-1488: UserDefinedPredicate throw NPE

- parquet-benchmarks/run.sh
- https://issues.apache.org/jira/browse/PARQUET-1600
No additional test since it's a really minor change. I ran the modified script via tcsh and confirmed that it worked as expected.
> PARQUET-1600: Fix shebang in parquet-benchmarks/run.sh

- README.md
- dev/travis-before_install.sh
- https://issues.apache.org/jira/browse/PARQUET-1654
No additional test, since it's a fix for the CI script. I confirmed the CI succeeded with this fix on Travis using my GitHub repository.
> PARQUET-1654: Remove unnecessary options when building thrift

- parquet-cli/pom.xml
- parquet-hadoop/pom.xml
- parquet-jackson/pom.xml
- parquet-pig/pom.xml
- parquet-thrift/pom.xml
- pom.xml
Make sure you have checked _all_ steps below: https://jira.apache.org/jira/browse/PARQUET-1649
- https://issues.apache.org/jira/browse/PARQUET-1649
> PARQUET-1649: Bump Jackson Databind to 2.9.9.3

- parquet-common/pom.xml
- https://issues.apache.org/jira/browse/PARQUET-1671
No additional tests, since it's a depnedent library upgrade. I confirmed that all existent tests succeeded as regression tests.
> PARQUET-1671: Upgrade Yetus to 0.11.0

- pom.xml
- https://issues.apache.org/jira/browse/PARQUET-1673
> PARQUET-1673: Upgrade parquet-mr format version to 2.7.0

- parquet-avro/src/test/java/org/apache/parquet/avro/TestArrayCompatibility.java
- parquet-avro/src/test/java/org/apache/parquet/avro/TestAvroSchemaConverter.java
- parquet-column/src/main/java/org/apache/parquet/io/api/Binary.java
- parquet-column/src/test/java/org/apache/parquet/schema/TestTypeBuilders.java
- parquet-column/src/test/java/org/apache/parquet/schema/TestTypeUtil.java
- parquet-common/src/test/java/org/apache/parquet/bytes/TestByteBufferInputStreams.java
- parquet-common/src/test/java/org/apache/parquet/io/TestDelegatingSeekableInputStream.java
- parquet-common/src/test/java/org/apache/parquet/util/TestDynConstructors.java
- parquet-common/src/test/java/org/apache/parquet/util/TestDynMethods.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileWriter.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/PrintFooter.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestMemoryManager.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestParquetWriter.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestParquetWriterAppendBlocks.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/util/TestHadoop2ByteBufferReads.java
To improve on readability and reduce boilerplate code.
https://jira.apache.org/jira/browse/PARQUET-1578
> PARQUET-1578 Introduce Lambdas

- parquet-column/src/main/java/org/apache/parquet/schema/LogicalTypeAnnotation.java
- parquet-hadoop/src/main/java/org/apache/parquet/format/converter/ParquetMetadataConverter.java
- parquet-hadoop/src/test/java/org/apache/parquet/format/converter/TestParquetMetadataConverter.java
> PARQUET-1682: Maintain forward compatibility for TIME/TIMESTAMP

- parquet-protobuf/pom.xml
- parquet-thrift/pom.xml
> PARQUET-1691: Build fails due to missing hadoop-lzo

- parquet-column/src/main/java/org/apache/parquet/column/EncodingStats.java
- parquet-column/src/main/java/org/apache/parquet/schema/GroupType.java
- parquet-hadoop/src/main/java/org/apache/parquet/ParquetReadOptions.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ColumnChunkPageReadStore.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/MemoryManager.java
> PARQUET-1723: Read From Maps Without Using Contains

- parquet-avro/src/main/java/org/apache/parquet/avro/AvroConverters.java
- parquet-avro/src/main/java/org/apache/parquet/avro/AvroRecordConverter.java
- parquet-cli/src/main/java/org/apache/parquet/cli/json/AvroJson.java
- parquet-column/src/main/java/org/apache/parquet/CorruptDeltaByteArrays.java
- parquet-column/src/main/java/org/apache/parquet/CorruptStatistics.java
- parquet-column/src/main/java/org/apache/parquet/column/impl/ColumnReadStoreImpl.java
- parquet-column/src/main/java/org/apache/parquet/column/values/plain/BinaryPlainValuesReader.java
- parquet-column/src/main/java/org/apache/parquet/filter2/predicate/Operators.java
- parquet-common/src/main/java/org/apache/parquet/VersionParser.java
- parquet-common/src/main/java/org/apache/parquet/util/DynConstructors.java
- parquet-common/src/main/java/org/apache/parquet/util/DynMethods.java
- parquet-encoding/src/main/java/org/apache/parquet/column/values/bitpacking/Packer.java
- parquet-format-structures/src/main/java/org/apache/parquet/format/event/Consumers.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/DirectCodecFactory.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetInputFormat.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetOutputFormat.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/metadata/ParquetMetadata.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/util/ContextUtil.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/util/HadoopStreams.java
- parquet-pig/src/main/java/org/apache/parquet/pig/TupleWriteSupport.java
- parquet-pig/src/main/java/org/apache/parquet/pig/convert/TupleConverter.java
- parquet-pig/src/main/java/org/apache/parquet/pig/summary/SummaryData.java
- parquet-thrift/src/main/java/org/apache/parquet/hadoop/thrift/ThriftBytesWriteSupport.java
- parquet-thrift/src/main/java/org/apache/parquet/hadoop/thrift/ThriftReadSupport.java
- https://issues.apache.org/jira/browse/PARQUET-1726
> PARQUET-1726: Use Java 8 Multi Exception Handling

- parquet-pig/src/main/java/org/apache/parquet/pig/ParquetLoader.java
- https://issues.apache.org/jira/browse/PARQUET-1727
> PARQUET-1727: Do Not Swallow InterruptedException in ParquetLoader

- parquet-cli/src/main/java/org/apache/parquet/cli/csv/RecordBuilder.java
- parquet-cli/src/main/java/org/apache/parquet/cli/util/GetClassLoader.java
- parquet-column/src/main/java/org/apache/parquet/filter2/recordlevel/FilteringGroupConverter.java
- parquet-column/src/main/java/org/apache/parquet/internal/column/columnindex/BinaryColumnIndexBuilder.java
- parquet-column/src/main/java/org/apache/parquet/io/PrimitiveColumnIO.java
- parquet-column/src/main/java/org/apache/parquet/io/RecordReaderImplementation.java
- parquet-hadoop/src/main/java/org/apache/parquet/format/converter/ParquetMetadataConverter.java
- parquet-tools/src/main/java/org/apache/parquet/tools/command/MetadataUtils.java
- parquet-tools/src/main/java/org/apache/parquet/tools/util/MetadataUtils.java
- https://issues.apache.org/jira/browse/PARQUET-1732
> PARQUET-1732: Call toArray With Empty Array

- dev/finalize-release
- parquet-benchmarks/pom.xml
- parquet-cli/pom.xml
- parquet-tools/pom.xml
- pom.xml
> PARQUET-1703: Update API compatibility check

- parquet-column/src/main/java/org/apache/parquet/filter2/recordlevel/FilteringRecordMaterializer.java
- https://issues.apache.org/jira/browse/PARQUET-1741
> PARQUET-1741: Restore APIs to keep backward compatibility

- parquet-column/src/main/java/org/apache/parquet/column/values/bloomfilter/BlockSplitBloomFilter.java
- parquet-column/src/main/java/org/apache/parquet/column/values/bloomfilter/BloomFilter.java
- parquet-column/src/test/java/org/apache/parquet/column/values/bloomfilter/TestBlockSplitBloomFilter.java
> PARQUET-1743: Add equals method

- parquet-avro/src/main/java/org/apache/parquet/avro/AvroRecordConverter.java
> PARQUET-1782: Use Switch Statement in AvroRecordConverter

- pom.xml
- https://issues.apache.org/jira/browse/PARQUET-1796
> PARQUET-1796: Bump Avro from 1.9.1 to 1.9.2

- parquet-tools/src/main/java/org/apache/parquet/tools/command/PruneColumnsCommand.java
- parquet-tools/src/main/java/org/apache/parquet/tools/command/Registry.java
- parquet-tools/src/test/java/org/apache/parquet/tools/command/TestPruneColumnsCommand.java
> PARQUET-1791: Add 'prune' command to parquet-tools

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/InternalParquetRecordReader.java
- https://issues.apache.org/jira/browse/PARQUET-1759
> PARQUET-1759: InternalParquetRecordReader Use Singleton Set

- parquet-column/src/main/java/org/apache/parquet/column/ColumnProperty.java
- parquet-column/src/main/java/org/apache/parquet/column/ParquetProperties.java
- parquet-column/src/main/java/org/apache/parquet/column/values/factory/DefaultValuesWriterFactory.java
- parquet-column/src/test/java/org/apache/parquet/column/values/factory/DefaultValuesWriterFactoryTest.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ColumnConfigParser.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetOutputFormat.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetWriter.java
> PARQUET-1784: Column-wise configuration

- parquet-column/src/main/java/org/apache/parquet/example/data/simple/SimpleGroup.java
- parquet-column/src/main/java/org/apache/parquet/io/MessageColumnIO.java
- parquet-column/src/test/java/org/apache/parquet/io/ExpectationValidatingConverter.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestInputFormat.java
- https://issues.apache.org/jira/browse/PARQUET-1808
> [PARQUET-1808]: Replacing multiple String Object creations with StringBuilder

- dev/COMMITTERS.md
> Add 'shangxinli' to committers list 

- parquet-column/src/main/java/org/apache/parquet/column/ParquetProperties.java
- parquet-column/src/main/java/org/apache/parquet/column/impl/ColumnWriteStoreBase.java
- parquet-column/src/main/java/org/apache/parquet/column/impl/ColumnWriterBase.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetOutputFormat.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetWriter.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestBloomFiltering.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestParquetWriter.java
> PARQUET-1805: Refactor the configuration for bloom filters

- .travis.yml
- parquet-benchmarks/src/main/resources/log4j.properties
- parquet-format-structures/pom.xml
- parquet-hadoop/src/test/java/org/apache/parquet/statistics/TestStatistics.java
- parquet-hadoop/src/test/resources/log4j.properties
- parquet-pig/src/test/resources/log4j.properties
- parquet-protobuf/src/test/resources/log4j.properties
- pom.xml
> PARQUET-1832: Travis fails with too long output

- parquet-common/pom.xml
addresses [PARQUET-1699](https://issues.apache.org/jira/browse/PARQUET-1699)
> PARQUET-1699: upgrade yetus to 0.12.0

- parquet-cascading-common23/src/main/java/org/apache/parquet/cascading/TupleReadSupport.java
- parquet-cli/pom.xml
- parquet-cli/src/main/java/org/apache/parquet/cli/commands/ParquetMetadataCommand.java
- parquet-cli/src/main/java/org/apache/parquet/cli/commands/ShowPagesCommand.java
- parquet-cli/src/main/java/org/apache/parquet/cli/csv/CSVProperties.java
- parquet-hadoop/src/test/java/org/apache/parquet/filter2/dictionarylevel/DictionaryFilterTest.java
- pom.xml
> PARQUET-1844: Eliminate using commons-lang

- parquet-hadoop/README.md
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/MemoryManager.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetOutputFormat.java
> PARQUET-1826: Document Hadoop configuration options

- pom.xml
- https://issues.apache.org/jira/browse/PARQUET-1842.
- No new functionality
> PARQUET-1842: Update jackson-databind version

- parquet-avro/src/test/java/org/apache/parquet/avro/TestCircularReferences.java
- https://issues.apache.org/jira/browse/PARQUET-1763
> PARQUET-1763: Add SLF4J to TestCircularReferences

- pom.xml
- https://issues.apache.org/jira/browse/PARQUET-1756
> PARQUET-1756: Remove Dependency on Maven Plugin semantic-versioning

- parquet-protobuf/pom.xml
- parquet-protobuf/src/main/java/org/apache/parquet/proto/ProtoWriteSupport.java
- parquet-protobuf/src/test/java/org/apache/parquet/proto/ProtoInputOutputFormatTest.java
- parquet-protobuf/src/test/java/org/apache/parquet/proto/ProtoWriteSupportTest.java
- parquet-protobuf/src/test/java/org/apache/parquet/proto/TestUtils.java
addresses https://issues.apache.org/jira/browse/PARQUET-1684
> PARQUET-1684: dont store default protobuf values as null for proto3

- parquet-avro/src/main/java/org/apache/parquet/avro/AvroParquetReader.java
- parquet-avro/src/test/java/org/apache/parquet/avro/TestReadWrite.java
> PARQUET-1778: Do Not Consider Class for Avro Generic Record Reader

- .travis.yml
- parquet-hadoop/README.md
- parquet-hadoop/src/test/java/org/apache/parquet/crypto/keytools/samples/VaultClient.java
hadoop/readme.md, travis.yaml, vault sample fixes
> PARQUET-1891: encryption fixes

- parquet-avro/src/test/java/org/apache/parquet/avro/TestReadWrite.java
- parquet-avro/src/test/java/org/apache/parquet/avro/TestStringBehavior.java
- pom.xml
> PARQUET-1890: Upgrade to Avro 1.10.0

- pom.xml
- https://issues.apache.org/jira/browse/PARQUET-1895
> PARQUET-1895: Update jackson-databind

- pom.xml
> PARQUET-1923: upgrade hadoop from 2.7.3 to 2.10.1

- parquet-cli/src/main/java/org/apache/parquet/cli/commands/TransCompressionCommand.java
- parquet-cli/src/test/java/org/apache/parquet/cli/MainTest.java
- parquet-cli/src/test/java/org/apache/parquet/cli/commands/TransCompressionCommandTest.java
- https://issues.apache.org/jira/browse/PARQUET-1910
> PARQUET-1910: Fix broken parquet-cli

- pom.xml
> [PARQUET-1932] Bump Fastutil to 8.4.2

- parquet-tools/pom.xml
> PARQUET-1941: Bump Commons CLI from 1.3.1 to 1.4

- parquet-hadoop/src/main/java/org/apache/parquet/crypto/keytools/FileKeyUnwrapper.java
- parquet-hadoop/src/main/java/org/apache/parquet/crypto/keytools/FileKeyWrapper.java
- parquet-hadoop/src/main/java/org/apache/parquet/crypto/keytools/HadoopFSKeyMaterialStore.java
- parquet-hadoop/src/main/java/org/apache/parquet/crypto/keytools/KeyToolkit.java
> PARQUET-1938: Key rotation - option to get KMS details from key material

- parquet-cli/src/main/java/org/apache/parquet/cli/Main.java
- parquet-cli/src/main/java/org/apache/parquet/cli/commands/ColumnMaskingCommand.java
- parquet-column/src/main/java/org/apache/parquet/column/ColumnWriter.java
- parquet-column/src/main/java/org/apache/parquet/column/impl/ColumnWriterBase.java
- parquet-column/src/test/java/org/apache/parquet/io/TestColumnIO.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ColumnChunkPageWriteStore.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileWriter.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/util/ColumnMasker.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/util/CompressionConverter.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/util/ColumnMaskerTest.java
- parquet-tools/src/main/java/org/apache/parquet/tools/command/ColumnMaskingCommand.java
- parquet-tools/src/main/java/org/apache/parquet/tools/command/PruneColumnsCommand.java
- parquet-tools/src/main/java/org/apache/parquet/tools/command/Registry.java
> PARQUET-1915: Add nullify column

- parquet-cli/src/main/java/org/apache/parquet/cli/Main.java
- parquet-cli/src/main/java/org/apache/parquet/cli/commands/PruneColumnsCommand.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/util/ColumnPruner.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/util/ColumnPrunerTest.java
- parquet-tools/src/main/java/org/apache/parquet/tools/command/PruneColumnsCommand.java
> [PARQUET-1801] Add parquet-tools 'prune' to parquet-cli

- pom.xml
> PARQUET-1952: Upgrade Avro to 1.10.1

- parquet-tools/src/main/java/org/apache/parquet/tools/command/DumpCommand.java
My PR addresses the following [PARQUET-1954](https://issues.apache.org/jira/browse/PARQUET-1954T/)
does not need testing
> PARQUET-1954: TCP connection leak in parquet dump

- parquet-cli/src/main/java/org/apache/parquet/cli/commands/TransCompressionCommand.java
- parquet-tools/src/main/java/org/apache/parquet/tools/command/TransCompressionCommand.java
> PARQUET-1949: Mark Parquet-1872 with note support bloom filter yet

- pom.xml
> PARQUET-1961: Bump Jackson to 2.11.4

- parquet-column/src/main/java/org/apache/parquet/filter2/compat/FilterCompat.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/InternalParquetRecordReader.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestColumnIndexFiltering.java
> PARQUET-1964: Properly handle missing/null filter

- .github/workflows/test.yml
- pom.xml
> PARQUET-1969: Test by GithubAction

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java
> PARQUET-1964: FOLLOWUP: Avoid constructing useless ArrayList

- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestMemoryManager.java
> PARQUET-1971: Flaky test in github action

- parquet-column/src/main/java/org/apache/parquet/internal/column/columnindex/OffsetIndex.java
- parquet-common/src/main/java/org/apache/parquet/io/OutputFile.java
- parquet-hadoop/src/main/java/org/apache/parquet/crypto/keytools/PropertiesDrivenCryptoFactory.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetWriter.java
- pom.xml
> PARQUET-1970: Make minor releases source compatible

- pom.xml
> PARQUET-1966: Fix build with JDK11 for JDK8

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/Offsets.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileWriter.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/metadata/ColumnChunkMetaData.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestParquetFileWriter.java
> PARQUET-1977: Invalid data_page_offset

- .travis.yml
As requested at https://issues.apache.org/jira/browse/PARQUET-1980?focusedCommentId=17297220&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17297220
> PARQUET-1980 Update Maven profile from 'travis' to 'ci-test'

- parquet-protobuf/pom.xml
> PARQUET-1493: Fix protobuf plugin for proxies

- pom.xml
- https://issues.apache.org/jira/browse/PARQUET-2001
> PARQUET-2001: Bump Avro from 1.10.1 to 1.10.2

- parquet-cli/src/main/java/org/apache/parquet/cli/Main.java
- parquet-cli/src/main/java/org/apache/parquet/cli/commands/ShowFooterCommand.java
- parquet-cli/src/test/java/org/apache/parquet/cli/commands/ShowFooterCommandTest.java
- parquet-format-structures/src/main/java/org/apache/parquet/format/CliUtils.java
> PARQUET-1978: Provide a tool to show the complete footer

- parquet-cascading-deprecated/pom.xml
- parquet-cascading3-deprecated/pom.xml
- parquet-scrooge-deprecated/pom.xml
> PARQUET-2010: Fix japicmp issues

- README.md
- dev/ci-before_install.sh
- parquet-format-structures/src/main/java/org/apache/parquet/format/CliUtils.java
- parquet-format-structures/src/main/java/org/apache/parquet/format/InterningProtocol.java
- parquet-format-structures/src/main/java/org/apache/parquet/format/Util.java
- parquet-thrift/src/main/java/org/apache/parquet/hadoop/thrift/ThriftBytesWriteSupport.java
- parquet-thrift/src/main/java/org/apache/parquet/thrift/BufferedProtocolReadToWrite.java
- parquet-thrift/src/main/java/org/apache/parquet/thrift/ParquetProtocol.java
- parquet-thrift/src/test/java/org/apache/parquet/thrift/TestProtocolReadToWrite.java
- pom.xml
> PARQUET-2005: Upgrade thrift to 0.14.1

- pom.xml
> PARQUET-2031: Upgrade to parquet-format 2.9.0

- parquet-column/src/main/java/org/apache/parquet/io/BaseRecordReader.java
> PARQUET-2048: Deprecate BaseRecordReader

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/MemoryManager.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetMemoryManagerRuntimeException.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestMemoryManager.java
> PARQUET-2063: Remove Compile Warnings from MemoryManager

- parquet-column/src/test/java/org/apache/parquet/ResourceIntensiveTestRule.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestLargeColumnChunk.java
- pom.xml
> PARQUET-2059: Handle resource-intensive tests in CI

- CHANGES.md
> Update CHANGES.md for 1.12.1

- parquet-column/src/main/java/org/apache/parquet/io/ColumnIO.java
> PARQUET-2083: Expose getFieldPath from ColumnIO

- README.md
- dev/ci-before_install.sh
- pom.xml
- [X ] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
- All the public functions and the classes in the …
> PARQUET-2084: Upgrade Thrift to 0.14.2

- README.md
- dev/ci-before_install.sh
- pom.xml
- https://issues.apache.org/jira/browse/PARQUET-2096
> PARQUET-2096: Upgrade Thrift to 0.15.0

- .travis.yml
> PARQUET-2107: Fix Travis failures

- README.md
- dev/ci-before_install.sh
- pom.xml
> PARQUET-2128: Upgrade Thrift to 0.16.0

- parquet-cli/src/main/java/org/apache/parquet/cli/commands/ParquetMetadataCommand.java
Just adding an additional line to the log
> PARQUET-2129: Add uncompressedSize to meta Command

- pom.xml
- https://issues.apache.org/jira/browse/PARQUET-2169
> PARQUET-2169: Upgrade Avro to version 1.11.1

- pom.xml
> PARQUET-2191: Upgrade Scala to 2.12.17

- parquet-hadoop/README.md
Document the hadoop parameter for uniform encryption
> PARQURT-2197: Document uniform encryption

- parquet-column/src/main/java/org/apache/parquet/column/values/bitpacking/ByteBitPackingValuesReader.java
Minor performance improvements for ByteBitPackingValuesReader:
- Move object creation (temporary byte array) out of frequently used code by retaining small temporary buffer as class member.
- Move less frequently used code (readMore) into separate function to encourage JIT to inline more frequently used code (readInteger)
- Avoid use of unpack8Values that takes ByteBuffer, because it's slower.
> Performance optimization to ByteBitPackingValuesReader

- parquet-column/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java
Jira: [PARQUET-2246](https://issues.apache.org/jira/browse/PARQUET-2246)
> PARQUET-2246: Add short circuit logic to column index filter

- dev/COMMITTERS.md
> Add Gang Wu as committer

- README.md
- dev/COMMITTERS.md
And add myself to the list of committers
- https://issues.apache.org/jira/browse/PARQUET-2269
> PARQUET-2269: Update version in README.md

- parquet-plugins/parquet-encoding-vector/pom.xml
- parquet-plugins/parquet-plugins-benchmarks/pom.xml
> MINOR: update version of disabled module to 1.13.1-SNAPSHOT

- dev/COMMITTERS.md
> Add gershinsky to COMMITTERS.md

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java
For Iceberg/Flink we would like to run without the hadoop dependencies. The use of the HiddenFileFilter is blocking this. This replaces the filter with a nice stream.
```
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/PathFilter
at org.apache.iceberg.parquet.ReadConf.newReader(ReadConf.java:232)
at org.apache.iceberg.parquet.ReadConf.<init>(ReadConf.java:80)
at org.apache.iceberg.parquet.ParquetReader.init(ParquetReader.java:71)
at org.apache.iceberg.parquet.ParquetReader.iterator(ParquetReader.java:91)
at org.apache.iceberg.parquet.ParquetReader.iterator(ParquetReader.java:37)
at org.apache.iceberg.util.Filter.lambda$filter$0(Filter.java:34)
at org.apache.iceberg.io.CloseableIterable$2.iterator(CloseableIterable.java:72)
at …
```
> PARQUET-2283: Remove Hadoop HiddenFileFilter

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java
For Iceberg/Flink we would like to run without the hadoop dependencies. The use of the HiddenFileFilter is blocking this. This replaces the filter with a nice stream.
- https://issues.apache.org/jira/browse/PARQUET-2283
- All the public functions and the classes in the PR contain Javadoc …
> PARQUET-2283: Remove Hadoop HiddenFileFilter (#1072)

- pom.xml
> PARQUET-2290: Fix CI

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetRecordReader.java
https://issues.apache.org/jira/browse/PARQUET-2297
> PARQUET-2297: Skip delta problem check for encrypted files

- .gitignore
- pom.xml
> PARQUET-2319: Upgrade Avro to version 1.11.2

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/rewrite/ParquetRewriter.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/rewrite/ParquetRewriterTest.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/util/TestFileBuilder.java
> PARQUET-2343: Fixes NPE when rewriting file with multiple rowgroups

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/metadata/ParquetMetadata.java
> Use try-with-resources

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileWriter.java
IDEA was lighting up as a christmas tree :)
> MINOR: Modest refactor of ParquetFileWriter

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/metadata/ParquetMetadata.java
Make sure you have checked _all_ steps below. 
> Remove old setting for cascading

- pom.xml
> PARQUET-2360 Upgrade Avro to version 1.11.3

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileWriter.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/rewrite/ParquetRewriter.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/rewrite/ParquetRewriterTest.java
This PR adds support for encrypting the V2 page header when encrypting/re-encrypting files.
> PARQUET-2363: ParquetRewriter should encrypt the V2 page header

- pom.xml
- https://issues.apache.org/jira/browse/PARQUET-2368
> PARQUET-2368: Update japicmp to 1.18.1

- parquet-hadoop/README.md
- parquet-hadoop/src/main/java/org/apache/parquet/crypto/keytools/PropertiesDrivenCryptoFactory.java
- parquet-hadoop/src/test/java/org/apache/parquet/crypto/TestPropertiesDrivenEncryption.java
> PARQUET-2370: Crypto factory activation of "all column encryption" mode

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/rewrite/ParquetRewriter.java
This patch aims to reduce the unnecessary RowGroup data reading during rewriting.
> PARQUET-2372: Avoid unnecessary reading of RowGroup data during rewriting

- parquet-avro/src/test/java/org/apache/parquet/avro/TestReadWrite.java
- parquet-common/src/main/java/org/apache/parquet/conf/PlainParquetConfiguration.java
- pom.xml
> PARQUET-2359: Add simple plain Parquet configuration implementation

- parquet-arrow/pom.xml
- parquet-arrow/src/main/java/org/apache/parquet/arrow/schema/List3Levels.java
- parquet-arrow/src/main/java/org/apache/parquet/arrow/schema/Map3Levels.java
- parquet-arrow/src/main/java/org/apache/parquet/arrow/schema/SchemaConverter.java
- parquet-arrow/src/main/java/org/apache/parquet/arrow/schema/SchemaMapping.java
- parquet-arrow/src/test/java/org/apache/parquet/arrow/schema/TestSchemaConverter.java
- parquet-column/src/main/java/org/apache/parquet/schema/LogicalTypeAnnotation.java
- pom.xml
This bumps Arrow many versions:
- Some API's have changed around the field.
- Add support for converting a map and also added a test.
- https://issues.apache.org/jira/browse/PARQUET-1942
> PARQUET-1942: Bump Arrow to 14.0.1

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/rewrite/ParquetRewriter.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/rewrite/RewriteOptions.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/util/HadoopInputFile.java
- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/util/HadoopOutputFile.java
- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/rewrite/ParquetRewriterTest.java
- Parameterized testing within ParquetRewriterTest using the new unhadooped methods.
> PARQUET-2380: Decouple rewriter from Hadoop

- parquet-column/src/main/java/org/apache/parquet/filter/ColumnPredicates.java
- parquet-column/src/main/java/org/apache/parquet/filter/PagedRecordFilter.java
They are easier to read
- https://issues.apache.org/jira/browse/PARQUET-2390
> PARQUET-2390: Replace anonymous functions with lambdas

- .asf.yaml
- https://issues.apache.org/jira/browse/PARQUET-2407
- All …
> PARQUET-2407: Minimize settings in jira_options of .asf.yaml

- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestInterOpReadFloat16.java
- https://issues.apache.org/jira/browse/PARQUET-1647
- https://github.com/apache/parquet-mr/pull/1142
> PARQUET-1647: Add Float16 Interoperability Tests

- README.md
This change adds the `-j` flag to `sudo make install` so that copy-pasters, like myself, have it a little easier.
This change does not reference any Jira issue because it is so extremely small.
1. Subject uses the …
> chore: improve Thrift install instructions

- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/rewrite/ParquetRewriterTest.java
> MINOR: try to fix github workflow timeout

- parquet-hadoop/README.md
- https://issues.apache.org/jira/browse/PARQUET-2426
- All …
> PARQUET-2426: Add lz4_raw compression to README

- pom.xml
Apr 4, 2024
https://github.com/luben/zstd-jni/releases/tag/v1.5.6-2
Mar 28, 2024
https://github.com/luben/zstd-jni/releases/tag/v1.5.6-1
Dec 1, 2023
https://github.com/luben/zstd-jni/releases/tag/v1.5.5-11
> PARQUET-2461: Upgrade ZSTD-JNI to 1.5.6-2

- CHANGES.md
> Update release note for 1.14.0

- README.md
- dev/ci-before_install.sh
- pom.xml
0.20.0 comes with Homebrew.
- To apply the necessary changes, run `mvn …
> PARQUET-2462: Bump to Thrift 0.20.0

- CHANGES.md
Forgot to update the list.
- To apply the necessary changes, run `mvn …
> Update changes for the `parquet-1.14.x` branch

- CHANGES.md
> Update changes for the `master` branch

- parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetWriter.java
I think this is easier to read
- https://issues.apache.org/jira/browse/PARQUET-2466
- To apply the necessary changes, run `mvn …
> PARQUET-2466: Simplify logic when calling `ParquetWriter`

- README.md
> Update readme to point to 1.14.0 release

- parquet-hadoop/pom.xml
- https://issues.apache.org/jira/browse/PARQUET-2487
- All …
> PARQUET-2487: Bump io.airlift:aircompressor from 0.26 to 0.27

- parquet-hadoop/pom.xml
Fixes a CVE
cc @wgtmac 
- https://issues.apache.org/jira/browse/PARQUET-2487
- To apply the necessary changes, run `mvn spotless:apply …
> PARQUET-2487: Bump io.airlift:aircompressor from 0.26 to 0.27 (#1363)

- parquet-avro/src/main/resources/META-INF/NOTICE
> Chore: Update NOTICE of parquet-avro

- .gitattributes
- [x ] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references
- [x ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
- [x ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines
1. Subject is separated from body by a …
> PARQUET-2494: Update git attribrutes to mark png as binary

- .asf.yaml
Reference: https://lists.apache.org/thread/w6r0fwj42wvpm5yflwxhtm2ss3z2hrl3
> Add github section in asf.yaml to enable issues

- README.md
Update `README.md` to point to 1.14.1 release
> Update readme to point to 1.14.1 release

- CHANGES.md
> Minor: `PARQUET-2472` is not in the `1.14.1` release

- pom.xml
> GH-3009: Bump zstd-jni.version from 1.5.6-3 to 1.5.6-6

- pom.xml
> GH-3021: Upgrade Avro dependency

- parquet-common/src/main/java/org/apache/parquet/bytes/BytesInput.java
Noticed this while reviewing https://github.com/apache/parquet-java/issues/3040
> MINOR: Throw exception in BytesInput

- pom.xml
> MINOR: Update `issueManagement` in `pom.xml`

- pom.xml
Some version bumps in the tooling:
https://github.com/apache/maven-apache-parent/releases/tag/apache-33
> MINOR: Bump Maven parent pom

- README.md
- dev/ci-before_install.sh
- pom.xml
This brings it in line with parquet-format:
https://github.com/apache/parquet-format/blob/dff0b3e6f02ed28e6b0753e921d53de53e63f506/pom.xml#L79
> MINOR: Bump Thrift to 0.21.0

- parquet-column/pom.xml
- parquet-common/pom.xml
- parquet-encoding/pom.xml
- parquet-format-structures/pom.xml
- parquet-thrift/pom.xml
- pom.xml
> MINOR: Use `exec-maven-plugin.version` property

- pom.xml
> MINOR: Remove `scala` properties from `pom.xml`

- README.md
- pom.xml
> MINOR: update latest version to 1.15.1

- pom.xml
> Bump Parquet Format to 2.11

- parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestParquetFileWriter.java
> minor: Cleanup some small bits in a test
